### ISSUE TITLE
Implement .txt input processor

### ISSUE THREAD

**Issue by selkind** [selkind/text_analysis#18]
## Expected behavior:
class that opens and reads .txt documents and returns a raw string

**Comment by BMSnider** [comment]
Hey,
I'm new to open source contributing. I'm looking for a project to learn how to use GitHub. I have already written the bulk of the class for the .txt to raw string. I just have to add some features I wanted to add and learn how to pull. I hope I can help

**Comment by selkind** [comment]
Awesome, welcome to the project! I'm also relatively new to Git and GitHub. I started this repo as a way to learn best practices for managing version control. You're the first external contributor I've had for a project, so it might take me some time to figure out the workflow. I'll be busy most of the afternoon today, but I'll be sure to check in on this issue tonight. 
Let me know if there's anything I can do to help!

**Comment by BMSnider** [comment]
I tried to make a pull request, but it changed me to my fork. I think I need to be cleared as a contributor.

**Comment by selkind** [comment]
I looked into this, and I think you do just need to create a pull request on your own fork and it will be tracked by my repository automatically. I'm basing that off of this page: https://gist.github.com/Chaser324/ce0505fbed06b947d962
Note the submitting section.

**Comment by selkind** [comment]
completed in PR #28
