### ISSUE TITLE
Enhance InputFilter.get_words

### ISSUE THREAD

**Issue by selkind** [selkind/text_analysis#22]
## Expected behavior:
Punctuation is removed from the trailing characters of words

## Actual behavior:
Punctuation is included as the final character of a word at the end of a sentence

## Steps required to reproduce actual behavior:
use InputFilter.get_words on a string with properly punctuated sentences.

## Average flightspeed of an unladen swallow:
What do you mean? African or European swallow?

**Comment by garroadran** [comment]
I can have a go at this if you'd like, but are you looking specifically to remove Latin alphabet punctuation, or do you expect to have to deal with non ascii characters as well?

**Comment by selkind** [comment]
Good question. I hadn't really considered this. Personally, I don't have much background working with different character sets or encodings. But now that I think about it, when working with data sources that aren't English, I would assume that dealing with non ascii characters is essential.

To fulfill the minimum needs of this particular issue, you're welcome to only deal with Latin alphabet punctuation, but if you'd like to also include non-ascii filtering functionality by all means go for it!

**Comment by garroadran** [comment]
Alright, I'll toss you a PR in a few hours, most likely.
Another thing worth thinking about is how you want to parse words. From the looks of it so far, I suspect you want to basically parse anything that's separated by spaces as separate words, but of course there are lots of edge cases like hyphenated words, words with slashes, and contracted words (for example, a lot of corpus analysis tools treat "do" and "n't" as separate words). For the moment though, I'll just put something together that will meet the basic need you have at present, and you can let me know if you want me to look into something more elaborate than that.

**Comment by selkind** [comment]
This is great input! 
Just some background on me:
This project came about just as a subject upon which I can practice/figure out Github, project management, software architecture, and unit testing (all things that I don't get experience with in my current job). I don't have any formal background in statistics (besides some college courses) or linguistics. 

As a result, I haven't really put much thought into the "business logic" that I'm aiming for. It's clear, just from this thread, that I have a lot to consider and you're much more knowledgeable than me on the subject. I do hope you'll stick around and continue to contribute because your experience will definitely speed up the design process. If you do plan to keep contributing here, I'd be interested to hear about your background and what you'd like out of this project. Also, if you have used a lot of other analysis tools, what gaps exist in their feature-sets that can be filled by this project.

I'll try to hash out a UML diagram of  the project that I'm envisioning in the next couple days so that we have some documentation with which we can focus our development efforts.

**Comment by garroadran** [comment]
A diagram would be cool. And yeah, I'll definitely keep a look out for any issues I think I can help out with.

My own background is largely in linguistics. I've done some academic work with corpora, and so I have a bit of experience in the field of doing computer-assisted textual analysis. I also work as a translator, so I have a professional interest in computer-assisted quality control, and that's what I've been putting a lot of brainpower into over the past year or so. However, as a computer scientist I'm still very much a beginner, so be sure to take anything I say with a grain of salt!
